# Generated by Django 3.0.3 on 2020-02-28 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookbook',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_cookbooks', to=settings.AUTH_USER_MODEL, verbose_name='starred by'),
        ),
    ]
