# Generated by Django 3.0.3 on 2020-02-28 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
        ('ingredient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0002_auto_20200228_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cookbooks',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='cookbook.Cookbook'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='ingredient.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_recipes', to=settings.AUTH_USER_MODEL, verbose_name='starred by'),
        ),
    ]
