name: django_cookbook
dependencies:
  - python=3.11.3
  - pip=23.0.1
  - pip:
      - django==4.2.2
      - djangorestframework==3.14.0
      - djangorestframework_simplejwt==5.2.2
      - django-filter==23.2
      - drf-yasg==1.21.5
