name: django_cookbook
dependencies:
  - python=3.6
  - pip:
      - django==3.0.3
      - djangorestframework==3.11.0
      - djangorestframework_simplejwt==4.4.0
      - django-filter==2.2.0
      - coreapi==2.3.3
      - Markdown==3.2.1
      - Pygments==2.5.2
